# DJ Universe - Production Secrets Template
# NOTE: These are template values. Replace with actual secrets in production.

apiVersion: v1
kind: Secret
metadata:
  name: dj-universe-secrets
  namespace: dj-universe-prod
  labels:
    app.kubernetes.io/name: dj-universe
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Database Passwords
  POSTGRES_PASSWORD: "REPLACE_WITH_SECURE_PASSWORD"
  MONGODB_PASSWORD: "REPLACE_WITH_SECURE_PASSWORD"
  REDIS_PASSWORD: "REPLACE_WITH_SECURE_PASSWORD"
  
  # JWT Secrets
  JWT_SECRET: "REPLACE_WITH_SECURE_JWT_SECRET"
  JWT_REFRESH_SECRET: "REPLACE_WITH_SECURE_REFRESH_SECRET"
  
  # External Service API Keys
  AWS_ACCESS_KEY_ID: "REPLACE_WITH_AWS_KEY"
  AWS_SECRET_ACCESS_KEY: "REPLACE_WITH_AWS_SECRET"
  CLOUDFLARE_API_KEY: "REPLACE_WITH_CLOUDFLARE_KEY"
  
  # OAuth Secrets
  GOOGLE_CLIENT_SECRET: "REPLACE_WITH_GOOGLE_SECRET"
  FACEBOOK_CLIENT_SECRET: "REPLACE_WITH_FACEBOOK_SECRET"
  SPOTIFY_CLIENT_SECRET: "REPLACE_WITH_SPOTIFY_SECRET"
  
  # Email Service
  SENDGRID_API_KEY: "REPLACE_WITH_SENDGRID_KEY"
  SMTP_PASSWORD: "REPLACE_WITH_SMTP_PASSWORD"
  
  # Monitoring
  GRAFANA_ADMIN_PASSWORD: "REPLACE_WITH_GRAFANA_PASSWORD"
  PROMETHEUS_PASSWORD: "REPLACE_WITH_PROMETHEUS_PASSWORD"
  
  # MinIO/S3
  MINIO_ROOT_PASSWORD: "REPLACE_WITH_MINIO_PASSWORD"
  S3_SECRET_KEY: "REPLACE_WITH_S3_SECRET"
  
  # AI Service API Keys
  OPENAI_API_KEY: "REPLACE_WITH_OPENAI_KEY"
  TENSORFLOW_SERVING_KEY: "REPLACE_WITH_TF_KEY"
  
  # CDN and Storage
  CDN_SECRET_KEY: "REPLACE_WITH_CDN_SECRET"
  STORAGE_ENCRYPTION_KEY: "REPLACE_WITH_STORAGE_KEY"
  
  # Session and Security
  SESSION_SECRET: "REPLACE_WITH_SESSION_SECRET"
  CSRF_SECRET: "REPLACE_WITH_CSRF_SECRET"
  ENCRYPTION_KEY: "REPLACE_WITH_ENCRYPTION_KEY"
  
  # Third-party Services
  STRIPE_SECRET_KEY: "REPLACE_WITH_STRIPE_SECRET"
  PAYPAL_CLIENT_SECRET: "REPLACE_WITH_PAYPAL_SECRET"
  
  # NDI and Streaming
  NDI_LICENSE_KEY: "REPLACE_WITH_NDI_LICENSE"
  OBS_WEBSOCKET_PASSWORD: "REPLACE_WITH_OBS_PASSWORD"
  
  # InfluxDB
  INFLUXDB_ADMIN_TOKEN: "REPLACE_WITH_INFLUX_TOKEN"
  INFLUXDB_PASSWORD: "REPLACE_WITH_INFLUX_PASSWORD"

---
# TLS Secrets for HTTPS
apiVersion: v1
kind: Secret
metadata:
  name: dj-universe-tls
  namespace: dj-universe-prod
  labels:
    app.kubernetes.io/name: dj-universe
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  # Replace with base64 encoded certificate and key
  tls.crt: LS0tLS1CRUdJTi... # Base64 encoded certificate
  tls.key: LS0tLS1CRUdJTi... # Base64 encoded private key

---
# Docker Registry Secret
apiVersion: v1
kind: Secret
metadata:
  name: dj-universe-registry
  namespace: dj-universe-prod
  labels:
    app.kubernetes.io/name: dj-universe
    app.kubernetes.io/component: registry
type: kubernetes.io/dockerconfigjson
data:
  # Replace with actual registry credentials
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlv... # Base64 encoded docker config